stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - sanjayan

deploy:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Triggering Render Deploy..."
    - curl -X POST "https://api.render.com/deploy/$RENDER_SERVICE_ID?key=$RENDER_API_KEY"
  only:
    - sanjayan
