import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Outfit, Oswald } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import Footer from "./components/Footer";
import { AppContextProvider } from "./context/AppContext";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const nunito = Nunito({ variable: "--font-nunito", subsets: ["latin"], weight: ["400", "700"] });
const outfit = Outfit({ variable: "--font-outfit", subsets: ["latin"], weight: ["400", "700"] });
const oswald = Oswald({ variable: "--font-oswald", subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${nunito.variable}
          ${outfit.variable}
          ${oswald.variable}
          antialiased
        `}
      >
        <Header />
        <AppContextProvider>

        <section>{children}</section>
        </AppContextProvider>
        <Footer/>
      </body>
    </html>
  );
}
